# Generated by Django 3.2.2 on 2021-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billpayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp2', models.CharField(max_length=200)),
                ('temp1', models.CharField(max_length=200)),
            ],
        ),
    ]
